//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSatış.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public string admin_surname { get; set; }
        public string admin_email { get; set; }
        public string admin_password_hash { get; set; }
        public string admin_password_salt { get; set; }
        public string admin_create_date { get; set; }
        public string admin_ip { get; set; }
        public byte[] admin_update_date { get; set; }
        public string admin_tel { get; set; }
    }
}
