//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSatış.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_detail
    {
        public long menu_detail_id { get; set; }
        public int food_id { get; set; }
        public long menu_id { get; set; }
    
        public virtual foods foods { get; set; }
        public virtual menu menu { get; set; }
    }
}
