//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSatış.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class evyemegiEntities : DbContext
    {
        public evyemegiEntities()
            : base("name=evyemegiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<Details> Details { get; set; }
        public virtual DbSet<district> district { get; set; }
        public virtual DbSet<food_catagory> food_catagory { get; set; }
        public virtual DbSet<foods> foods { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<menu_detail> menu_detail { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<street> street { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<town> town { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
