//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSatış.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public long order_id { get; set; }
        public long user_id { get; set; }
        public byte portion { get; set; }
        public System.DateTime order_create_date { get; set; }
        public byte order_status { get; set; }
        public long menu_id { get; set; }
        public decimal order_price { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual user user { get; set; }
    }
}
