//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSatış.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.Basket = new HashSet<Basket>();
            this.Details = new HashSet<Details>();
            this.food_catagory = new HashSet<food_catagory>();
            this.foods = new HashSet<foods>();
            this.menu = new HashSet<menu>();
            this.order = new HashSet<order>();
        }
    
        public long user_id { get; set; }
        public string user_nickname { get; set; }
        public string user_name { get; set; }
        public short city_id { get; set; }
        public short town_id { get; set; }
        public short district_id { get; set; }
        public int street_id { get; set; }
        public string user_email { get; set; }
        public string user_password_salt { get; set; }
        public bool user_active { get; set; }
        public Nullable<bool> user_status { get; set; }
        public System.DateTime user_create_date { get; set; }
        public string user_create_ip { get; set; }
        public System.DateTime user_update_date { get; set; }
        public long user_cep { get; set; }
        public Nullable<double> user_score { get; set; }
        public bool admin_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Details> Details { get; set; }
        public virtual district district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<food_catagory> food_catagory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foods> foods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu> menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        public virtual street street { get; set; }
        public virtual town town { get; set; }
    }
}
